# Generated by Django 4.1.3 on 2022-11-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('episodios', models.CharField(blank=True, max_length=255)),
                ('temporadas', models.CharField(blank=True, max_length=255)),
                ('lançamento', models.DateField()),
                ('sinopse', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('lançamento', models.DateField()),
                ('desenvolvedora', models.CharField(max_length=255)),
                ('descrição', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('especificações', models.TextField(blank=True)),
                ('peça', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.tipohardware')),
            ],
        ),
    ]
