# Generated by Django 4.1.3 on 2022-11-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animes',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='animes',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jogos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='jogos',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
