# Generated by Django 4.1.3 on 2022-11-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_animes_foto_animes_mostrar_hardware_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='modelo',
            new_name='nome',
        ),
    ]
